<?php

namespace ContainerD5Tdey5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JNB1nmXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JNB1nmX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JNB1nmX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.JNB1nmX.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.JNB1nmX": it references class "App\\Entity\\Article" but no such service exists.'],
            'repo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'repo' => 'App\\Repository\\ArticleRepository',
        ]);
    }
}
